// load
export const LOAD_MORE_TITLES = 'LOAD_MORE_TITLES';

// reset
export const RESET_STATE = 'RESET_STATE';

// search
export const NEW_SEARCH_REQUEST      = 'NEW_SEARCH_REQUEST';
export const RECEIVE_SEARCH_RESPONSE = 'RECEIVE_SEARCH_RESPONSE';
export const RECEIVE_SEARCH_ERROR    = 'RECEIVE_SEARCH_ERROR';

// sort
export const CHANGE_SORT_BY_OPTION = 'CHANGE_SORT_BY_OPTION';